#!/usr/bin/env bash

set -e
set -u

# Install vim-piug
echo "Installing vim-plug"

mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/undodir

curl -fLo \
  ~/.vim/autoload/plug.vim \
  --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
